sonar.sources=backend/app.py,backend/config.py,backend/models,backend/routes
sonar.tests=backend/Tests
sonar.exclusions=**/__pycache__/**,backend/static/**,backend/scripts/**,**/coverage.xml
sonar.python.coverage.reportPaths=backend/coverage.xml
